import { BaseCommand, args, flags } from '@adonisjs/core/ace'
import type { CommandOptions } from '@adonisjs/core/types/ace'
import Video from '#models/video'
import QueueService from '#services/queue_service'
import drive from '@adonisjs/drive/services/main'

export default class RegenerateThumbnails extends BaseCommand {
  static commandName = 'thumbnails:regenerate-all'
  static description = 'Regenerate all thumbnails (force re-generation even if they exist)'

  @args.string({ description: 'Process only specific video ID', required: false })
  declare videoId: string

  @flags.boolean({ description: 'Delete old thumbnails before regenerating' })
  declare deleteOld: boolean

  static options: CommandOptions = {
    startApp: true,
  }

  async run() {
    this.logger.info('🔄 Regenerating all thumbnails...')

    try {
      // Get videos to process
      let videos: Video[]

      if (this.videoId) {
        const video = await Video.find(this.videoId)
        if (!video) {
          this.logger.error(`Video ${this.videoId} not found`)
          return
        }
        videos = [video]
      } else {
        videos = await Video.query().where('is_published', true).orderBy('created_at', 'desc')
      }

      this.logger.info(`Found ${videos.length} videos to regenerate`)

      const queueService = new QueueService()
      let queued = 0
      let errors = 0

      for (const video of videos) {
        const thumbnailKey = `thumbnails/${video.id}.jpg`

        try {
          // Optionally delete old thumbnail
          if (this.deleteOld) {
            try {
              await drive.use('spaces').delete(thumbnailKey)
              this.logger.info(`🗑️  Deleted old thumbnail for video ${video.id}`)
            } catch {
              // File didn't exist, that's fine
            }
          }

          // Queue thumbnail generation
          await queueService.addJob('videoProcessing', {
            videoId: video.id,
            filePath: video.filePath,
          })

          this.logger.info(`🎬 Queued thumbnail regeneration for video ${video.id}`)
          queued++
        } catch (queueError) {
          this.logger.error(`❌ Failed to queue job for video ${video.id}:`, queueError)
          errors++
        }
      }

      this.logger.info('')
      this.logger.success('Thumbnail regeneration complete!')
      this.logger.info(`📊 Stats: ${queued} queued, ${errors} errors`)

      if (queued > 0) {
        this.logger.info('')
        this.logger.info('💡 Thumbnails are being generated by the worker.')
        this.logger.info('   Check logs: docker logs memebank_workers_dev -f')
      }
    } catch (error) {
      this.logger.error('Failed to regenerate thumbnails:', error)
    }
  }
}
